fix: apiVersion and kind from CRD in registration
In `CustomResourceOperationsImpl` construction
`KubernetesDeserializer::registerCustomKind` is invoked without
`apiVersion` and with `kind` set to the class name. This could lead to
issues when deserializing custom resources, in my example:

```
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:camel.apache.org/v1alpha1#Integration
 at [Source: (String)"{"type":"DELETED","object":{"apiVersion":"camel.apache.org/v1alpha1","kind":"Integration","metadata":{"annotations":{"prometheus.io/port":"9779","prometheus.io/scrape":"true","syndesis.io/deploy-id":"i-M0SZstrdU_fCuujYkqGz:2","syndesis.io/deployment-version":"2","syndesis.io/integration-id":"i-M0SZstrdU_fCuujYkqGz","syndesis.io/integration-name":"t2l"},"creationTimestamp":"2020-02-19T13:14:10Z","generation":1,"labels":{"syndesis.io/app":"syndesis","syndesis.io/component":"integration","syndesis."[truncated 3644 chars]; line: 1, column: 4142] (through reference chain: io.fabric8.kubernetes.api.model.WatchEvent["object"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271) ~[jackson-databind-2.10.2.jar:2.10.2]
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78) ~[kubernetes-model-4.6.1.jar:4.6.1]
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:33) ~[kubernetes-model-4.6.1.jar:4.6.1]
```

Because only `"Integration"` would be registered, whereas type lookup is
using `apiVersion` and `kind.

This changes that to specify the `apiVersion` and `kind` based on the
definition given in the `CustomResource`.